---
title: "Genetic Algorithms and Neural Networks"
format: html
sidebar:
    contents:
      - section: "Notebooks"
        contents: 
          - notebooks/exerc_kfold_cv.ipynb
          - notebooks/exerc_strat_kfold_cv.ipynb
---
  
## Introduction to Machine Learning

- [Slides](slides/intro_ml.qmd)

### Reading

- James, G., Witten, D., Hastie, T., Tibshirani, R., & Taylor, J. (2023). *An introduction to statistical learning: With applications in Python.* Springer. [https://www.statlearning.com](https://www.statlearning.com)
  - Chapter 5: Resampling Methods

### Exercises
- [Exercise 1](notebooks/exerc_kfold_cv.ipynb)
- [Exercise 2](notebooks/exerc_strat_kfold_cv.ipynb)

## Feed-Forward Neural Networks

- [Slides](slides/feed_forward_neural_networks.qmd)

### Reading

- Bishop, C. M., & Bishop, H. (2024). *Deep learning: Foundations and concepts.* Springer. [https://www.bishopbook.com](https://www.bishopbook.com)
  - Chapter 6: Deep Neural Networks
  - Chapter 7: Gradient Descent
  - Chapter 8: Backpropagation
- Chollet, F. (2021). *Deep learning with Python (2nd ed.).* Manning Publications.
  - Chapter 2: The mathematical building blocksof neural networks
  - Chapter 4: Getting started with neural networks: Classification and regression
- James, G., Witten, D., Hastie, T., Tibshirani, R., & Taylor, J. (2023). *An introduction to statistical learning: With applications in Python.* Springer. [https://www.statlearning.com](https://www.statlearning.com)
  - Chapter 10: Deep Learning
- Zhang, A., Lipton, Z. C., Li, M., & Smola, A. J. (2023). *Dive into deep learning.* Cambridge University Press. [https://d2l.ai](https://d2l.ai)
  - Chapter 3: Linear Neural Networks for Regression
  - Chapter 4: Linear Neural Networks for Classification
  - Chapter 5: Multilayer Perceptrons

## References

- Bishop, C. M., & Bishop, H. (2024). *Deep learning: Foundations and concepts.* Springer. [https://www.bishopbook.com](https://www.bishopbook.com)

- Chollet, F. (2021). *Deep learning with Python (2nd ed.).* Manning Publications.

- James, G., Witten, D., Hastie, T., Tibshirani, R., & Taylor, J. (2023). *An introduction to statistical learning: With applications in Python.* Springer. [https://www.statlearning.com](https://www.statlearning.com)

- Zhang, A., Lipton, Z. C., Li, M., & Smola, A. J. (2023). *Dive into deep learning.* Cambridge University Press. [https://d2l.ai](https://d2l.ai)
